export const GET_USERS_REQUESTED      = " GET_USERS_REQUESTED"
export const SET_USERS_REQUESTED      = "SET_USERS_REQUESTED"
export const UPDATE_USER_REQUESTED    = "UPDATE_USER_REQUESTED"
export const REMOVE_USERS_REQUESTED   = "REMOVE_USERS_REQUESTED"

export const GET_GROUPS_REQUESTED     = "GET_GROUPS_REQUESTED"
export const SET_GROUP_REQUESTED      = "SET_GROUP_REQUESTED"
export const UPDATE_GROUP_REQUESTED   = "SET_GROUP_REQUESTED"
export const REMOVE_GROUP_REQUESTED   = "REMOVE_GROUP_REQUESTED"

export const SET_MESSAGE_REQUESTED    = "SET_MESSAGE_REQUESTED"
export const GET_MESSAGES_REQUESTED   = "SET_MESSAGES_REQUESTED"
export const REMOVE_MESSAGE_REQUESTED = "REMOVE_MESSAGE_REQUESTED"

export const GET_ADMIN_REQUESTED      = "GET_ADMIN_REQUESTED"
export const UPDATE_ADMIN_REQUESTED   = "UPDATE_ADMIN_REQUESTED"

export const GET_CHART_MONTH_REQUESTED= "GET_CHART_MONTH_REQUESTED"
export const GET_CHART_DAY_REQUESTED  = "GET_CHART_DAY_REQUESTED"

export const SET_IMAGE_REQUESTED      = "SET_IMAGE_REQUESTED"

export const RESET_SETTING_REQUESTED  = "RESET_SETTING_REQUESTED"
