export const GET_USERS_REQUESTED      = " GET_USERS_REQUESTED"
export const SET_USERS_REQUESTED      = "SET_USERS_REQUESTED"
export const REMOVE_USERS_REQUESTED   = "REMOVE_USERS_REQUESTED"

export const GET_GROUPS_REQUESTED     = "GET_GROUPS_REQUESTED"
export const SET_GROUP_REQUESTED      = "SET_GROUP_REQUESTED"
export const REMOVE_GROUP_REQUESTED   = "REMOVE_GROUP_REQUESTED"

export const SET_MESSAGE_REQUESTED    = "SET_MESSAGE_REQUESTED"
export const GET_MESSAGES_REQUESTED   = "SET_MESSAGES_REQUESTED"
export const REMOVE_MESSAGE_REQUESTED = "REMOVE_MESSAGE_REQUESTED"
